### ISSUE TITLE
install of numpy 1.26.0 fails

### ISSUE THREAD

**Issue by Lonelysoulman** [talss89/termux-home-assistant-installer#10]
hi,
i just upgraded to homeassistant 2023.10.0 and after startup of homeassistant i get the error 
Setup failed for stream: Requirements for stream not found: ['numpy==1.26.0'].

the log when it tries to install numpy:
Unable to install package numpy==1.26.0: WARNING: Skip installing pip, this will break the python-pip package (termux).             error: subprocess-exited-with-error                               
  × pip subprocess to install backend dependencies did not run successfully.                            │ exit code: 1
  

i can workaround it with "hass -v --skip-pip-packages numpy" but i would like to fix it. any ideas?

is there a better way of updating ha with "pip install --upgrade homeassistant"? this way i run in new errors with every update

**Comment by romanovj** [comment]
```
pip uninstall numpy
pkg install python-numpy
```

**Comment by Lonelysoulman** [comment]
thanks
