### ISSUE TITLE
some fixes from me

### ISSUE THREAD

**Issue by romanovj** [talss89/termux-home-assistant-installer#3]
1. For Termux numpy
hass -v --skip-pip-packages numpy

2. For fixing  ha-av with ffmpeg  6 try these commands:
Download
[ha-av-10.0.0.tar.gz](https://github.com/talss89/termux-home-assistant-installer/files/11413180/ha-av-10.0.0.tar.gz)
pip install build
Inside unpacked archive:
python -m build
cd dist
pip install *whl

(I installed ha-av outside of venv, venv was created with
python -m venv --without-pip --system-site-packages hass)

UPD, after upgrading ffmpeg "av" package should be deleted.
Should be here
 /data/data/com.termux/files/home/.homeassistant/deps/lib/python3.11/site-packages/av

or 

/data/data/com.termux/files/usrh/lib/python3.11/site-packages/av

or in venv

**Comment by talss89** [comment]
Amazing, thank you. Which HA version is this for?

It might be worth freezing the termux package repo at this point if most things are working without patching or recompiling.

**Comment by romanovj** [comment]
homeassistant              2023.5.2

I didn't test much, just used same config from my docker container HA and didn't see errors beside access to /proc directory

**Comment by talss89** [comment]
Great. I'll run an install now and check it out.

Thanks a lot for the info.

**Comment by romanovj** [comment]
also I use llvm and binutils-is-llvm instead of binutils

**Comment by romanovj** [comment]
I wrote bad commands, try new

**Comment by lvalibaba** [comment]
after update `ha-av` installing & update to `ffmpeg 6.0.2` I got `libavutil` error. Returned to `ffmpeg 5.1.2-7`.

**Comment by romanovj** [comment]
how to recreate error?

**Comment by lvalibaba** [comment]
> how to recreate error?

I dont't know.
I simply upgrade ffmpeg from 5.1.2-7 to 6 & install ha-av 10.0.0 from your.

after build:
```
Successfully built ha-av-10.0.0.tar.gz and ha_av-10.0.0-cp311-cp311-linux_i686.w                                                                                        hl
~/ha-av-10.0.0 $ cd dist
~/ha-av-10.0.0/dist $ pip install *whl
Processing ./ha_av-10.0.0-cp311-cp311-linux_i686.whl
Installing collected packages: ha-av
Successfully installed ha-av-10.0.0
```
after starting HA 2023.5.2 (ffmpeg 6.0.2)
```
2023-05-07 19:12:00.389 INFO (MainThread) [homeassistant.setup] Setting up stream
2023-05-07 19:12:00.410 ERROR (MainThread) [homeassistant.setup] Error during setup of component stream
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/components/stream/__init__.py", line 224, in async_setup
    from .recorder import async_setup_recorder
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/components/stream/recorder.py", line 9, in <module>
    import av
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.11/site-packages/av/__init__.py", line 20, in <module>
    from av import logging
ImportError: dlopen failed: cannot find "libavutil.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.11/site-packages/av/logging.cpython-311.so"
2023-05-07 19:12:00.448 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant

```
added: with your ha-av build, after downgrade ffmpeg all starting without errors.

**Comment by romanovj** [comment]
arm64

2023-05-07 20:13:13.250 INFO (MainThread) [homeassistant.setup] Setting up stream
2023-05-07 20:13:13.794 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.5 seconds

Did you install ffmpeg 6.0.2 static?

**Comment by romanovj** [comment]
I got the same error after removing ffmpeg

**Comment by lvalibaba** [comment]
> arm64
> 
> 2023-05-07 20:13:13.250 INFO (MainThread) [homeassistant.setup] Setting up stream 2023-05-07 20:13:13.794 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.5 seconds
> 
> Did you install ffmpeg 6.0.2 static?

I use: pkg install ffmpeg. After installation checked the version - with an error it was 6.0.2 Maybe I use very old architecture tablet?

**Comment by home83vi** [comment]
Thanks to talss89 I was able to install homeassistant 2023.5.3 , but I didn't understand how to fix ha-av.  Can anyone explain me well all the steps from the beginning.  Many thanks for help,

Samsung Tab S2 LineageOS 18.1

**Comment by lvalibaba** [comment]
> Thanks to talss89 I was able to install homeassistant 2023.5.3 , but I didn't understand how to fix ha-av. Can anyone explain me well all the steps from the beginning. Many thanks for help,
> 
> Samsung Tab S2 LineageOS 18.1

1. Install libraries:
`pkg i freetype game-music-emu libaom libandroid-glob libass libbluray libbz2 libdav1d libgnutls libiconv liblzma libmp3lame libopus librav1e libsoxr libssh libtheora libvorbis libvpx libvidstab libwebp libx264 libx265 libxml2 libzimg littlecms ocl-icd xvidcore zlib opencl-headers jq`

2. install latest ffmpeg
`pkg install ffmpeg`

3.  install pkg from first post
`pip install (path_to_folder)/ha-av-10.0.0.tar.gz`

**Comment by home83vi** [comment]
> > Thanks to talss89 I was able to install homeassistant 2023.5.3 , but I didn't understand how to fix ha-av. Can anyone explain me well all the steps from the beginning. Many thanks for help,
> > Samsung Tab S2 LineageOS 18.1
> 
> 1. Install libraries:
>    `pkg i freetype game-music-emu libaom libandroid-glob libass libbluray libbz2 libdav1d libgnutls libiconv liblzma libmp3lame libopus librav1e libsoxr libssh libtheora libvorbis libvpx libvidstab libwebp libx264 libx265 libxml2 libzimg littlecms ocl-icd xvidcore zlib opencl-headers jq`
> 2. install latest ffmpeg
>    `pkg install ffmpeg`
> 3. install pkg from first post
>    `pip _install (path_to_folder)/ha-av-10.0.0.tar.gz`

Step 1 and 2 were successful.
 The problem I can't understand the 3 step ( 3. install pkg from first post
 > `pip _install (path_to_folder)/ha-av-10.0.0.tar.gz`)

 Please could you help me!  Explaining all the steps.
 Thank you very much

**Comment by lvalibaba** [comment]
> Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> 
> > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> 
> Please could you help me! Explaining all the steps. Thank you very much
1. Download from first post file `ha-av-10.0.0.tar.gz`
2. Install it
3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`

**Comment by home83vi** [comment]
> > Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> > > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> > 
> > 
> > Please could you help me! Explaining all the steps. Thank you very much
> 
> 1. Download from first post file `ha-av-10.0.0.tar.gz`
> 2. Install it
> 3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`

Thanks for help!
 Now I managed to solve with HA-AV but I have the problem with Numpy....
![20230519_211508](https://github.com/talss89/termux-home-assistant-installer/assets/78299609/f7b90ea4-ce54-414d-9f35-10d75784f6e8)

(hass) ~ $ pip list                                     Package                    Version                      -------------------------- --------                     aiohttp                    3.8.4                        aiohttp-cors               0.7.0                        aiosignal                  1.3.1                        anyio                      3.6.2                        astral                     2.2                          async-timeout              4.0.2                        atomicwrites-homeassistant 1.4.1                        attrs                      22.2.0                       awesomeversion             22.9.0                       bcrypt                     4.0.1                        certifi                    2023.5.7                     cffi                       1.15.1                       charset-normalizer         3.1.0                        ciso8601                   2.3.0                        cryptography               40.0.2                       frozenlist                 1.3.3                        h11                        0.14.0                       ha-av                      10.0.0                       home-assistant-bluetooth   1.10.0                       homeassistant              2023.5.3                     httpcore                   0.17.1                       httpx                      0.24.0                       idna                       3.4                          ifaddr                     0.1.7                        Jinja2                     3.1.2                        lru-dict                   1.1.8                        MarkupSafe                 2.1.2                        maturin                    0.15.2                       multidict                  6.0.4                        numpy                      1.24.3                       orjson                     3.8.10                       pip                        23.1.2                       pycparser                  2.21                         PyJWT                      2.6.0                        PyNaCl                     1.5.0                        pyOpenSSL                  23.1.0                       python-slugify             4.0.1                        PyTurboJPEG                1.6.7                        pytz                       2023.3                       PyYAML                     6.0                          requests                   2.28.2                       setuptools                 67.7.2                       sniffio                    1.3.0                        text-unidecode             1.3                          typing_extensions          4.5.0                        tzdata                     2023.3                       ulid-transform             0.7.2                        urllib3                    1.26.15                      voluptuous                 0.13.1                       voluptuous-serialize       2.6.0                        webrtcvad                  2.0.10                       wheel                      0.40.0                       yarl                       1.9.2               

The problem may be that I have an updated version of Numpy 1.24.3?

**Comment by lvalibaba** [comment]
> > > Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> > > > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> > > 
> > > 
> > > Please could you help me! Explaining all the steps. Thank you very much
> > 
> > 
> > 
> > 1. Download from first post file `ha-av-10.0.0.tar.gz`
> > 2. Install it
> > 3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`
> 
> Thanks for help! Now I managed to solve with HA-AV but I have the problem with Numpy.... ![20230519_211508](https://user-images.githubusercontent.com/78299609/239617249-f7b90ea4-ce54-414d-9f35-10d75784f6e8.jpg)
> 
> (hass) ~ $ pip list Package Version -------------------------- -------- aiohttp 3.8.4 aiohttp-cors 0.7.0 aiosignal 1.3.1 anyio 3.6.2 astral 2.2 async-timeout 4.0.2 atomicwrites-homeassistant 1.4.1 attrs 22.2.0 awesomeversion 22.9.0 bcrypt 4.0.1 certifi 2023.5.7 cffi 1.15.1 charset-normalizer 3.1.0 ciso8601 2.3.0 cryptography 40.0.2 frozenlist 1.3.3 h11 0.14.0 ha-av 10.0.0 home-assistant-bluetooth 1.10.0 homeassistant 2023.5.3 httpcore 0.17.1 httpx 0.24.0 idna 3.4 ifaddr 0.1.7 Jinja2 3.1.2 lru-dict 1.1.8 MarkupSafe 2.1.2 maturin 0.15.2 multidict 6.0.4 numpy 1.24.3 orjson 3.8.10 pip 23.1.2 pycparser 2.21 PyJWT 2.6.0 PyNaCl 1.5.0 pyOpenSSL 23.1.0 python-slugify 4.0.1 PyTurboJPEG 1.6.7 pytz 2023.3 PyYAML 6.0 requests 2.28.2 setuptools 67.7.2 sniffio 1.3.0 text-unidecode 1.3 typing_extensions 4.5.0 tzdata 2023.3 ulid-transform 0.7.2 urllib3 1.26.15 voluptuous 0.13.1 voluptuous-serialize 2.6.0 webrtcvad 2.0.10 wheel 0.40.0 yarl 1.9.2
> 
> The problem may be that I have an updated version of Numpy 1.24.3?

If you have old device `i32`, then maybe was installing problem with numpy.
Try `MATHLIB=m pip install numpy==1.23.2`

**Comment by romanovj** [comment]
> > > Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> > > > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> > > 
> > > 
> > > Please could you help me! Explaining all the steps. Thank you very much
> > 
> > 
> > 
> > 1. Download from first post file `ha-av-10.0.0.tar.gz`
> > 2. Install it
> > 3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`
> 
> Thanks for help! Now I managed to solve with HA-AV but I have the problem with Numpy.... ![20230519_211508](https://user-images.githubusercontent.com/78299609/239617249-f7b90ea4-ce54-414d-9f35-10d75784f6e8.jpg)
> 
> (hass) ~ $ pip list Package Version -------------------------- -------- aiohttp 3.8.4 aiohttp-cors 0.7.0 aiosignal 1.3.1 anyio 3.6.2 astral 2.2 async-timeout 4.0.2 atomicwrites-homeassistant 1.4.1 attrs 22.2.0 awesomeversion 22.9.0 bcrypt 4.0.1 certifi 2023.5.7 cffi 1.15.1 charset-normalizer 3.1.0 ciso8601 2.3.0 cryptography 40.0.2 frozenlist 1.3.3 h11 0.14.0 ha-av 10.0.0 home-assistant-bluetooth 1.10.0 homeassistant 2023.5.3 httpcore 0.17.1 httpx 0.24.0 idna 3.4 ifaddr 0.1.7 Jinja2 3.1.2 lru-dict 1.1.8 MarkupSafe 2.1.2 maturin 0.15.2 multidict 6.0.4 numpy 1.24.3 orjson 3.8.10 pip 23.1.2 pycparser 2.21 PyJWT 2.6.0 PyNaCl 1.5.0 pyOpenSSL 23.1.0 python-slugify 4.0.1 PyTurboJPEG 1.6.7 pytz 2023.3 PyYAML 6.0 requests 2.28.2 setuptools 67.7.2 sniffio 1.3.0 text-unidecode 1.3 typing_extensions 4.5.0 tzdata 2023.3 ulid-transform 0.7.2 urllib3 1.26.15 voluptuous 0.13.1 voluptuous-serialize 2.6.0 webrtcvad 2.0.10 wheel 0.40.0 yarl 1.9.2
> 
> The problem may be that I have an updated version of Numpy 1.24.3?

you can try to run with termux provided numpy (python-numpy)
hass -v --skip-pip-packages numpy

**Comment by home83vi** [comment]
> > > > Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> > > > > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> > > > 
> > > > 
> > > > Please could you help me! Explaining all the steps. Thank you very much
> > > 
> > > 
> > > 
> > > 1. Download from first post file `ha-av-10.0.0.tar.gz`
> > > 2. Install it
> > > 3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`
> > 
> > 
> > Thanks for help! Now I managed to solve with HA-AV but I have the problem with Numpy.... ![20230519_211508](https://user-images.githubusercontent.com/78299609/239617249-f7b90ea4-ce54-414d-9f35-10d75784f6e8.jpg)
> > (hass) ~ $ pip list Package Version -------------------------- -------- aiohttp 3.8.4 aiohttp-cors 0.7.0 aiosignal 1.3.1 anyio 3.6.2 astral 2.2 async-timeout 4.0.2 atomicwrites-homeassistant 1.4.1 attrs 22.2.0 awesomeversion 22.9.0 bcrypt 4.0.1 certifi 2023.5.7 cffi 1.15.1 charset-normalizer 3.1.0 ciso8601 2.3.0 cryptography 40.0.2 frozenlist 1.3.3 h11 0.14.0 ha-av 10.0.0 home-assistant-bluetooth 1.10.0 homeassistant 2023.5.3 httpcore 0.17.1 httpx 0.24.0 idna 3.4 ifaddr 0.1.7 Jinja2 3.1.2 lru-dict 1.1.8 MarkupSafe 2.1.2 maturin 0.15.2 multidict 6.0.4 numpy 1.24.3 orjson 3.8.10 pip 23.1.2 pycparser 2.21 PyJWT 2.6.0 PyNaCl 1.5.0 pyOpenSSL 23.1.0 python-slugify 4.0.1 PyTurboJPEG 1.6.7 pytz 2023.3 PyYAML 6.0 requests 2.28.2 setuptools 67.7.2 sniffio 1.3.0 text-unidecode 1.3 typing_extensions 4.5.0 tzdata 2023.3 ulid-transform 0.7.2 urllib3 1.26.15 voluptuous 0.13.1 voluptuous-serialize 2.6.0 webrtcvad 2.0.10 wheel 0.40.0 yarl 1.9.2
> > The problem may be that I have an updated version of Numpy 1.24.3?
> 
> If you have old device `i32`, then maybe was installing problem with numpy. Try `MATHLIB=m pip install numpy==1.23.2

I get errors:
![Screenshot_20230520-095312_Termux](https://github.com/talss89/termux-home-assistant-installer/assets/78299609/9df3f041-6e0b-4d3b-9490-7aaa5a41ba9a)

The device is a:  Samsung Galaxy Tab S2 T810, cpu 64bit.

**Comment by home83vi** [comment]
> > > > Step 1 and 2 were successful. The problem I can't understand the 3 step ( 3. install pkg from first post
> > > > > `pip install (path_to_folder)/ha-av-10.0.0.tar.gz`)
> > > > 
> > > > 
> > > > Please could you help me! Explaining all the steps. Thank you very much
> > > 
> > > 
> > > 
> > > 1. Download from first post file `ha-av-10.0.0.tar.gz`
> > > 2. Install it
> > > 3. If `ffmeg 5.X.X` was installed before, after the installation you need to delete the deps folder `deps`. I had it in `termux` along the path `~/.homeassistant/deps`
> > 
> > 
> > Thanks for help! Now I managed to solve with HA-AV but I have the problem with Numpy.... ![20230519_211508](https://user-images.githubusercontent.com/78299609/239617249-f7b90ea4-ce54-414d-9f35-10d75784f6e8.jpg)
> > (hass) ~ $ pip list Package Version -------------------------- -------- aiohttp 3.8.4 aiohttp-cors 0.7.0 aiosignal 1.3.1 anyio 3.6.2 astral 2.2 async-timeout 4.0.2 atomicwrites-homeassistant 1.4.1 attrs 22.2.0 awesomeversion 22.9.0 bcrypt 4.0.1 certifi 2023.5.7 cffi 1.15.1 charset-normalizer 3.1.0 ciso8601 2.3.0 cryptography 40.0.2 frozenlist 1.3.3 h11 0.14.0 ha-av 10.0.0 home-assistant-bluetooth 1.10.0 homeassistant 2023.5.3 httpcore 0.17.1 httpx 0.24.0 idna 3.4 ifaddr 0.1.7 Jinja2 3.1.2 lru-dict 1.1.8 MarkupSafe 2.1.2 maturin 0.15.2 multidict 6.0.4 numpy 1.24.3 orjson 3.8.10 pip 23.1.2 pycparser 2.21 PyJWT 2.6.0 PyNaCl 1.5.0 pyOpenSSL 23.1.0 python-slugify 4.0.1 PyTurboJPEG 1.6.7 pytz 2023.3 PyYAML 6.0 requests 2.28.2 setuptools 67.7.2 sniffio 1.3.0 text-unidecode 1.3 typing_extensions 4.5.0 tzdata 2023.3 ulid-transform 0.7.2 urllib3 1.26.15 voluptuous 0.13.1 voluptuous-serialize 2.6.0 webrtcvad 2.0.10 wheel 0.40.0 yarl 1.9.2
> > The problem may be that I have an updated version of Numpy 1.24.3?
> 
> you can try to run with termux provided numpy (python-numpy) hass -v --skip-pip-packages numpy

Everything seems to work, but I get this warning:
![Screenshot_20230520-100103_Chrome](https://github.com/talss89/termux-home-assistant-installer/assets/78299609/75a6cdd6-e98c-4159-8553-7b02b6bfdb46)
