### ISSUE TITLE
Error install Samsung A71 

### ISSUE THREAD

**Issue by home83vi** [talss89/termux-home-assistant-installer#5]
I'm having this error:
![Screenshot_20230514-172018_Termux](https://github.com/talss89/termux-home-assistant-installer/assets/78299609/fe457d64-3aa6-4448-b859-bd3242d5b560)

**Comment by talss89** [comment]
I'm going to need more information than that.

1. If you're including output (which you should be), please don't screenshot. Paste the full output of the command and wrap in backticks (`). It'll let me copy sections out, and search engines will point other people with the same problem this way.
2. Your screenshot doesn't include output from the process that returned the error. Please include all output.
3. Samsung A71, but what version of Android, are you rooted?
4. What steps were taken to result in this error?

I'm going to close this issue, but feel free to reopen with the details above.
