### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by Lonelysoulman** [talss89/termux-home-assistant-installer#7]
How can i install HACS?
When i try it says :

ERROR: Could not find the directory for Home Assistant

But im in the virtual enviroment. from where i start hass.
You mentioned problems with packages but how can i solve this?

**Comment by romanovj** [comment]
standart location for HA config
~/.homeassistant

you should execute this from termux home directory or HA directory
cd ~
or
cd ~/.homeassistant

wget -O - https://get.hacs.xyz | bash -

**Comment by Lonelysoulman** [comment]
thats what i tried. in both, the hass enviroment and in termux ~/... itself. both give the same error.

when i try to cd into /.suroot/.homeassistant (the only place where i could find the .homeassistant directory, its starting 
but i get the eror: 
mkdir: cannot create directory ‘/data/data/com.termux/files/home/.suroot/.homeassistant/custom_components’: Permission denied

im too new to termux and homeassistant to know what to do here. would be happy about additional help

**Comment by romanovj** [comment]
> thats what i tried. in both, the hass enviroment and in termux ~/... itself. both give the same error.
> 
> when i try to cd into /.suroot/.homeassistant (the only place where i could find the .homeassistant directory, its starting but i get the eror: mkdir: cannot create directory ‘/data/data/com.termux/files/home/.suroot/.homeassistant/custom_components’: Permission denied
> 
> im too new to termux and homeassistant to know what to do here. would be happy about additional help

did you start hass with "sudo hass"? 

then you need to execute script with root rights

sudo bash
wget -O - https://get.hacs.xyz | bash -

**Comment by Lonelysoulman** [comment]
thanks so much. that did the trick. but with a weird behavior. after enter the comand termux was instantly ready to receive next command  ( ~$ ). i wondered and decided to exit out of termux. and after entering "exit" it started installing.

and yeah. the readme says its better to run hass with sudo. so i did. shouldn't i do that?

**Comment by romanovj** [comment]
> thanks so much. that did the trick. but with a weird behavior. after enter the comand termux was instantly ready to receive next command ( ~$ ). i wondered and decided to exit out of termux. and after entering "exit" it started installing.
> 
> and yeah. the readme says its better to run hass with sudo. so i did. shouldn't i do that?

with root it's better to run HA core in chroot ubuntu
