### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by Lonelysoulman** [talss89/termux-home-assistant-installer#8]
Invalid config
The following integrations and platforms could not be set up:

[cloud](https://www.home-assistant.io/integrations/cloud) 
[stream](https://www.home-assistant.io/integrations/stream) 
[mobile_app](https://www.home-assistant.io/integrations/mobile_app) 
[assist_pipeline](https://www.home-assistant.io/integrations/assist_pipeline) 
[default_config](https://www.home-assistant.io/integrations/default_config)
Please check your config and [logs](http://192.168.178.21:8123/config/logs).

in the log it shows for mobile app (the one i really need) it shows:

Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: assist_pipeline, cloud, mobile_app, stream')
02:04:30 – (FEHLER) setup.py
Unable to set up dependencies of default_config. Setup failed for dependencies: assist_pipeline, cloud, mobile_app, stream
02:04:30 – (FEHLER) setup.py
Setup failed for cloud: Unable to import component: Exception importing homeassistant.components.cloud
02:04:30 – (FEHLER) setup.py - Die Nachricht ist zum ersten Mal am 02:04:19 aufgetreten und erscheint 3 mal
Unexpected exception importing component homeassistant.components.cloud
02:04:30 – (FEHLER) deps/lib/python3.11/site-packages/webrtcvad.py - Die Nachricht ist zum ersten Mal am 02:04:19 aufgetreten und erscheint 3 mal

i even tried a complete uninstall of termux and reinstalling  of hass via the installer script. i searched the web but nothing worked

**Comment by lvalibaba** [comment]
> Die Nachricht ist zum ersten Mal am 02:04:19 aufgetreten und erscheint 3 mal

After the script is completed, for versions above, you must additionally install webrtcvad: `pip install webrtcvad`

**Comment by Lonelysoulman** [comment]
i already found that but it didnt change anything. still the same invalid config.

i found pip install pyrfc3339 and this removed some of the errors at least. i still have:
The following integrations and platforms could not be set up:

[stream](https://www.home-assistant.io/integrations/stream) ([Show logs](http://192.168.178.21:8123/config/logs?filter=stream))
[default_config](https://www.home-assistant.io/integrations/default_config) ([Show logs](http://192.168.178.21:8123/config/logs?filter=default_config))

for default config the log: 
Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: stream')
22:44:35 – (ERROR) setup.py
Unable to set up dependencies of default_config. Setup failed for dependencies: stream
22:44:35 – (ERROR) setup.py

for stream:
Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: stream')
22:44:35 – (ERROR) setup.py
Unable to set up dependencies of default_config. Setup failed for dependencies: stream
22:44:35 – (ERROR) setup.py
Error during setup of component stream
22:44:02 – (ERROR) deps/lib/python3.11/site-packages/av/__init__.py

**Comment by romanovj** [comment]
try this variant (Home Assistant 2023.7.1) with **clean** termux

yes | pkg update
pkg install python make rust libcrypt libffi libjpeg-turbo llvm binutils-is-llvm libsodium ffmpeg libandroid-execinfo -y

python -m venv --without-pip hass
source hass/bin/activate

  pip install wheel
  pip install tzdata
  pip install maturin
  pip install setuptools
  pip install webrtcvad 
#your device API lvl
CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=**31**" MATHLIB=m pip install numpy==1.23.2
  pip install aiohttp_cors==0.7.0
  MATHLIB=m pip install PyTurboJPEG==1.6.7

  SODIUM_INSTALL=system pip install pynacl

  RUSTFLAGS="-C lto=n" CARGO_BUILD_TARGET="$(rustc -Vv | grep "host" | awk '{print $2}')" pip install homeassistant

hass -v

Pycares fix

wget https://files.pythonhosted.org/packages/01/50/e3015e6e03a3cf64113f509e8b86b71af37169b59ccedfcb182f3d031329/pycares-4.3.0.tar.gz

tar -xf pycares-4.3.0.tar.gz

sed -i s/'#define HAVE_GETSERVBYPORT_R 1'//g ./pycares-4.3.0/deps/build-config/config_android/ares_config.h

pip install ./pycares-4.3.0

**Comment by Lonelysoulman** [comment]
uff. is there no easier fix? why do i have this error? thought there only might be a problem with stream.

but i'll try next weekend

**Comment by romanovj** [comment]
> uff. is there no easier fix? why do i have this error? thought there only might be a problem with stream.
> 
> but i'll try next weekend

you can try to delete "av" and "ha-av" folders from ~/.homeassistant/deps

delete ffmpeg package and install newest one

install ha-av 10.0.1 from virtual env
pip install ha-av

**Comment by Lonelysoulman** [comment]
sry for my late reply. the repair option didnt work too. still the same invalid config. so i had to do the full reinstall. and that worked. thanks for your help
